const { env } = require('../config/env');

async function generateInterviewResponse({ question, assessmentName, domainCode, practiceCode }) {
  if (!env.CLAUDE_API_KEY) {
    return {
      answer: `Assessment guidance for ${assessmentName}: ${domainCode}/${practiceCode}. Confirm evidence ownership, assign a status, and keep connector/manual statuses authoritative.`,
      suggestedStatus: 'in_progress',
      source: 'ai'
    };
  }

  try {
    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': env.CLAUDE_API_KEY,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-3-5-sonnet-20241022',
        max_tokens: 400,
        messages: [{ role: 'user', content: `You are a CMMC readiness coach. Answer: ${question}. Assessment: ${assessmentName}. Domain: ${domainCode}. Practice: ${practiceCode}.` }]
      })
    });

    if (!response.ok) {
      throw new Error(`Anthropic call failed with ${response.status}`);
    }

    const data = await response.json();
    const text = data.content?.[0]?.text || 'AI guidance generated.';

    return {
      answer: text,
      suggestedStatus: 'in_progress',
      source: 'ai'
    };
  } catch (error) {
    console.error('Anthropic call failed:', error.message);
    return {
      answer: `Fallback guidance: validate the practice evidence, ensure the source remains authoritative, and assign the next operational status.`,
      suggestedStatus: 'in_progress',
      source: 'ai'
    };
  }
}

async function generateDocumentDraft({ documentType, assessment, organizationName }) {
  return {
    title: `${documentType.toUpperCase()} Draft - ${assessment.name}`,
    content: `# ${documentType.toUpperCase()} Draft\n\nOrganization: ${organizationName}\nAssessment: ${assessment.name}\n\nThis draft is generated by the backend service and requires human review before final approval.`
  };
}

module.exports = { generateInterviewResponse, generateDocumentDraft };
